### ISSUE TITLE
Playable Ogre

### ISSUE THREAD

**Issue by RHodzelmans** [ShinyHobo/PlayableMinotaur#4]
hi Shiny Hobo,

Hope you're well and safe from the pandemic. Sorry for the unconventional way of contacting, but I couldn't find a different way. I was hoping to leverage your knowledge (since you made a lot of the playable* mods to further my research for a mod inspired by you. You've made a great mod and it is relatively doable to follow. I've managed to get an Ogre playable character by modifying the Minotaur example you build and it works.

However, the poor bugger is naked. And for the life of me I can't find the way to dress him. Do you have tips on how to approach this? And say I do manage to solve it, would you willing - either under your name or mine - to expose them to the greater audience on a platform of your choice? I mostly made it for myself, but there are more people interested apparently and I don't particularly care about credit.

Happy to share what I've build, but the main changes are:

Races:

```
<!-- changed Parent ID -->
<!-- Minotaur is:  <attribute id="UUID" type="guid" value="31e1a2fe-0322-4540-95c3-9a28ad7fb202"/> -->
<!-- Naked Ogre is: <attribute id="UUID" type="guid" value="40af3916-df35-4e6e-aa8b-276cfc2c4f6f"/> -->
<!-- Melee Ogre is: <attribute id="UUID" type="guid" value="bc9fb0ff-18f1-4622-8260-d872e21a5b75"/> -->
<!-- Melee Ogre is: <attribute id="UUID" type="guid" value="535a319c-d578-4dd4-bfb2-4f7369ba6d67"/> -->
<!-- Melee Ogre is: <attribute id="UUID" type="guid" value="cfef7d2e-39f1-41c3-8b76-05d47b73fc16"/> -->
<attribute id="ParentGuid" type="guid" value="cfef7d2e-39f1-41c3-8b76-05d47b73fc16"/>
```

RootTemplates
```
<children>
	<!-- Ogre ...\UnpackedData\Shared\Public\Shared\RootTemplates\_merged.lsx 327334 -->
	<node id="GameObjects">
		<!-- Changed this -->
		<attribute id="Equipment" type="FixedString" value="EQP_Ogre_Club" />
		<!-- Changed this -->
		<attribute id="Icon" type="FixedString" 
                                  value="77a99f01-0b3d-484c-8fd7-b9f53c7178da-EQP_Ogre_Club_(Icon_Ogre)" />
		<attribute id="LevelName" type="FixedString" value="" />
		<attribute id="MapKey" type="FixedString" value="8d50a730-6199-4eba-84fc-266db2829adb" />
		<attribute id="Name" type="LSString" value="Ogre_867c3061-624e-4b02-babb-a23e743fb5d3" />
		<!-- 
			Changed this, controls the look in Game:
			Minotaur <attribute id="ParentTemplateId" type="FixedString" value="83a76ad4-29df-4e42-9926-16efa9d06088" /> 
			Ogre <attribute id="ParentTemplateId" type="FixedString" value="a28ef6b9-4dbb-4617-8345-37fe56101c29" /> 
		-->
		<attribute id="ParentTemplateId" type="FixedString" value="a28ef6b9-4dbb-4617-8345-37fe56101c29" /> 
		<!-- Changed this -->
		<attribute id="Stats" type="FixedString" value="Ogre" />
		<attribute id="Type" type="FixedString" value="character" />
		<!-- Changed this -->
		<attribute id="SpellSet" type="FixedString" value="CommonOgreActions" />
		<attribute id="_OriginalFileVersion_" type="int32" value="1073741871" />
```

Hope you have some tips for me! BTW: Great work on the Mod tool, it rocks. Haven't played around with the GameObject Explorer yet, but the rest is really great.

Much appreciated,

- Roel

**Comment by ShinyHobo** [comment]
Because of the way the game is set up, each race has its own set of clothes/armor specifically set up (ie Larian doesn't do any scaling or stretching to make something like gnome pants work on an elf). I would suggest looking at the GameObject Explorer and checking out the existing named Ogres as they do have clothes. The clothes that a character wears by default are stored in a visualbank entry.

I have not tested making those clothes physicalized and therefore swappable as I've been very busy.

You can find me on the Larian discord ([https://discord.gg/3WZRfcbvsG](https://discord.gg/3WZRfcbvsG)).
